local vimp = require('vimp')
vimp.nnoremap('<leader>hw', function()
  print("hello world")
end)
vimp.nnoremap('<leader>rr', function()
  math.randomseed(os.time())
  local a = math.random()
  vim.api.nvim_set_current_line(tostring(a))
end)
